Database Connection using doobie
47deg/github-alerts-scala-juan.quintero pull request #9
Opened 2023-09-21 19:44 UTC by MilenioX

This PR covers the implementation of the database connection for all the endpoints.
- Doobie dependency added
- Database connection implemented
- CQRS implemented to orchestrate services.
- Added Persistence Repositories definitions to execute SQL statements in the database.
- created generators utils to get uuids and current dates to use when building objects to store in database.
- Created DatabaseError to handle all the database errors
- Created DB Definitions to protect the domain in the core layer.
- Deleted unused implementations such as Cats-Equal instances for subscription and transformers from http input to domain model because now services receives specific fields and build domain objects in commands.
- **Removed test in services such as add and delete, because there is no state in unit tests, this will be handled with test-containers"
- **Removed Ref as Database: Deleting this implementation forced me to implemented all methods (that is the reason for the amount of changes)**
- **TEST CONTAINTERS: Will be implemented in following PRs, because of the amount of changes in this PR**

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/domain/generators.scala
> +    MonadThrow[F].pure(LocalDateTime.now())
Those are side-effects and thus should be properly suspended.
Also, **cats-effect** already provides good capabilities for those:
https://typelevel.org/cats-effect/api/3.x/cats/effect/std/UUIDGen.html
https://typelevel.org/cats-effect/api/3.x/cats/effect/kernel/Clock.html

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/domain/subscription.scala
> +  }
I would use an `enum` for this.

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/queries/GetSubscriptionsQry.scala
> +        MonadThrow[F].pure(_))
Check `MonadThrow.fromOption` and the `liftTo[F](error)` extension method to simplify all those conversions.

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/queries/GetUsersQuery.scala
> +      user <- userService.getUserById(userId)
Personal opinion, for this kind of methods I would rather do:

```scala
Logger[F].info(s"get users by id query called with id $userId") >>
userService.getUserById(userId)
```

Than doing a whole `for`, but his is just aesthetic preference.

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +  private def createService[F[_]: Async](): Resource[F, Server] =
This can _(should?)_ be a `val` :)

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +      .use(_ => IO.never)
`useFoerver` 😉

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +  def run(args: List[String]): IO[ExitCode] =
I would use `IOApp.Simple` which only needs

```scala
override final val run: IO[Unit] = ...
```

And leave the exit code handling to the library.

2023-09-21 20:13 UTC, BalmungSan commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +      .handleErrorWith(_ =>
And here I would just do an `onError`

2023-09-21 20:33 UTC, MilenioX commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/commands/SubscriptionCmd.scala
> +      _ = println(s"created subscription $newSubscription")
Opps!, my bad, thank you.

2023-09-21 21:39 UTC, MilenioX commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/queries/GetSubscriptionsQry.scala
> +        MonadThrow[F].pure(_))
Fixed

2023-09-21 21:40 UTC, MilenioX commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/queries/GetUsersQuery.scala
> +      user <- userService.getUserById(userId)
I agree, Done

2023-09-21 21:40 UTC, MilenioX commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +  private def createService[F[_]: Async](): Resource[F, Server] =
Done

2023-09-21 21:40 UTC, MilenioX commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +      .use(_ => IO.never)
Done

2023-09-21 21:40 UTC, MilenioX commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +  def run(args: List[String]): IO[ExitCode] =
Done

2023-09-21 21:40 UTC, MilenioX commented on subscription-service/ports/src/main/scala/com/jcq/gha/subscription/ports/Main.scala
> +      .handleErrorWith(_ =>
Done

2023-09-21 22:57 UTC, MilenioX commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/domain/generators.scala
> +    MonadThrow[F].pure(LocalDateTime.now())
Done

2023-09-21 23:12 UTC, MilenioX commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/domain/subscription.scala
> +  }
Done

2023-09-22 13:39 UTC, BalmungSan requested changes

2023-09-22 13:39 UTC, BalmungSan commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/domain/subscription.scala
> +  object subscriptionStatus extends Enumeration {
Don't use `Enumeration` like ever.
It was already broken and wrong in **Scala 2**, now in **Scala 3** we have `enum`

2023-09-22 13:40 UTC, BalmungSan commented on subscription-service/core/src/main/scala/com/jcq/gha/subscription/core/domain/subscription.scala
> +  object subscriptionStatus extends Enumeration {
Ah, wait, maybe this code is **Scala 2**? Sorry if I got confused.
If that is the case, then yeah, keep using `trait` + `case object` but then make the `trait` a `sealed` one.

2023-09-22 15:43 UTC, BalmungSan approved these changes

2023-09-22 15:50 UTC, merged